<?php

/**
 * @file
 * Contains reseau_mod_up_nonindexe.module.
 */



//Modification des formulaire
function reseau_mod_up_nonindexe_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id)
{
  if (is_array($form['#theme']) && in_array('node_form', $form['#theme'])) {

    if (($form_id === 'node_page_edit_form') || ($form_id === 'node_page_form')) {

      if (!empty($form['field_contenu_indexation'])) {
        $form['mycontainer'] = [
          '#type' => 'details',
          '#group' => 'advanced', // This line places the container in the sidebar
          '#weight' => 99,  // ensure it displays last or use -10 to show it first.
          '#title' => t('Indexation de la page'),
          '#tree' => TRUE,
          '#access' => TRUE,
        ];

        $form['field_contenu_indexation']['#weight'] = -1; // reset weight 
        $form['field_contenu_indexation']['#group'] = 'mycontainer';
      }
    }
  }
}


/**
 * Implements hook_preprocess_html() for html templates.
 */
function reseau_mod_up_nonindexe_preprocess_html(array &$variables)
{
  // Add META tag title + for Page non indexées
  // Load the node entity from current route.
  $node = \Drupal::routeMatch()->getParameter('node');
  if ($node) {

    // Check if node type is basic page.
    if ($node->getType() === 'page') {
      if (!empty($node->get('field_contenu_indexation')->getValue())) {
        if ($node->get('field_contenu_indexation')->getValue()[0]['value'] === '0') {

          $variables['page']['#attached']['html_head'][] = [
            [
              '#tag' => 'meta',
              '#attributes' => [
                'name' => 'robots',
                'content' => 'noindex, nofollow, noarchive, nosnippet, noodp, noydir, noimageindex, notranslate',
              ],
            ],
            'robots',
          ];
        }
      }
    }
  }
}
function reseau_mod_up_nonindexe_page_attachments_alter(array &$attachments)
{
  /*ajoute css admin*/
  $admin_theme = \Drupal::config('system.theme')->get('admin');
  $admin_theme_name = \Drupal::service('theme_handler')->getName($admin_theme);
  if ($admin_theme_name == 'Claro') {
    $attachments['#attached']['library'][] = 'reseau_mod_up_nonindexe/extra.indexation';
  }
}


/**
 * Implements hook_preprocess_menu().
 *
 * @param array[] $variables
 */
function reseau_mod_up_nonindexe_preprocess_menu(&$variables) {
  $current_user = \Drupal::entityTypeManager()->getStorage('user')->load(\Drupal::currentUser()->id());
      if (($current_user->hasRole('administrator')) || ($current_user->id() == '1')) {
        return;
      } else {
    // if (isset($variables['menu_name']) && $variables['menu_name'] === 'admin') {
    //   foreach($variables['items'] as $key => $item) {
  
    // if($variables['items'][$key]['title'] == 'Configuration'){
    //   dsm( $variables['items']);
    // }

    // }
    // }
    unset($variables['items']['system.admin_config']);
  }
  // }
}